[project]
name = "back-end"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "diffusers>=0.35.2",
    "modal>=1.2.0",
    "pydantic>=2.12.3",
    "torch>=2.9.0",
    "transformers>=4.57.1",
]
